#! /bin/sh

# Launch polybar
$HOME/.config/polybar/launch.sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 0
bspc config window_gap 45

bspc config split_ratio 0.52
bspc config borderless_monocle false
bspc config gapless_monocle false
